functionsDirectory = "C:\\Users\\HP\\Desktop\\-\\Do___Not__Entry==On clic at generate = 0func5457[```]\\vendza\\Frontend-vendza\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "C:\\Users\\HP\\Desktop\\-\\Do___Not__Entry==On clic at generate = 0func5457[```]\\vendza\\Frontend-vendza"
publishOrigin = "config"
functions = "C:\\Users\\HP\\Desktop\\-\\Do___Not__Entry==On clic at generate = 0func5457[```]\\vendza\\Frontend-vendza\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]